#! /bin/bash
project:project.o project_option.o array_option.o list_option.o tree_option.o hash_option.o graph_option.o other_option.o
	gcc -o project project.o project_option.o array_option.o list_option.o tree_option.o hash_option.o graph_option.o other_option.o

project_option:project_option.c header.h prototype.h
	gcc -cc project_option.c header.h prototype.h

#project option here
array_option:array_option.c header.h prototype.h
	gcc -c array_option.c header.h prototype.h
list_option:list_option.c header.h prototype.h
	gcc -c list_option.c header.h prototype.h
tree_option:tree_option.c header.h prototype.h
	gcc -c tree_option.c header.h prototype.h
hash_option:hash_option.c header.h prototype.h
	gcc -c hash_option.c header.h prototype.h
graph_option:grapth_option.c header.h prototype.h
	gcc -c stack.c header.h prototype.h
other_option:other_option.c header.h prototype.h
	gcc -c other_option.c header.h prototype.h

#array data structure option here
simple_array:simple_array.c header.h prototype.h array_prototype.h
	gcc -c simple_array.c header.h prototype.h array_prototype.h
bit_array:bit_array.c header.h prototype.h array_prototype.h
	gcc -c bit_array.c header.h prototype.h array_prototype.h
bit_field:bit_field.c header.h prototype.h array_prototype.h
	gcc -c bit_field.c header.h prototype.h array_prototype.h
bitboard:bitboard.c header.h prototype.h array_prototype.h
	gcc -c bitboard.c header.h prototype.h array_prototype.h
bitmap:bitmap.c header.h prototype.h array_prototype.h
	gcc -c bitmap.c header.h prototype.h array_prototype.h 
circular_buffer:circular_buffer.c header.h prototype.h array_prototype.h 
	gcc -c circular_buffer.c header.h prototype.h array_prototype.h
control_table:control_table.c header.h prototype.h array_prototype.h
	gcc -c control_table.c header.h prototype.h array_prototype.h
image:image.c header.h prototype.h array_prototype.h
	gcc -c image.c header.h prototype.h array_prototype.h
dope_array:dope_array.c header.h prototype.h array_prototype.h
	gcc -c dope_array.c header.h prototype.h array_prototype.h
dynamic_array:dynamic_array.c header.h prototype.h array_prototype.h
	gcc -c dynamic_array.c header.h prototype.h array_prototype.h
gap_buffer:gap_buffer.c header.h prototype.h array_prototype.h
	gcc -c gap_buffer.c header.h prototype.h array_prototype.h
hashed_array_tree:hashed_array_tree.c header.h prototype.h array_prototype.h
	gcc -c hashed_array_tree.c header.h prototype.h array_prototype.h
heightmap:heightmap.c header.h prototype.h array_prototype.h
	gcc -c heightmap.c header.h prototype.h array_prototype.h
lookup_table:lookup_table.c header.h prototype.h array_prototype.h
	gcc -c lookup_table.c header.h prototype.h array_prototype.h
matrix:matrix.c header.h prototype.h array_prototype.h
	gcc -c matrix.c header.h prototype.h array_prototype.h
parallel_array:parallel_array.c header.h prototype.h array_prototype.h
	gcc -c parallel_array.c header.h prototype.h array_prototype.h
sorted_array:sorted_array.c header.h prototype.h array_prototype.h
	gcc -c sorted_array.c header.h prototype.h array_prototype.h
sparse_array:sparse_array.c header.h prototype.h array_prototype.h
	gcc -c sparse_array.c header.h prototype.h array_prototype.h
iliffe_vector:iliffe_vector.c header.h prototype.h array_prototype.h
	gcc -c iliffe_vector.c header.h prototype.h array_prototype.h
variable_length_array:variable_length_array.c header.h prototype.h array_prototype.h
	gcc -c variable_length_array.c header.h prototype.h array_prototype.h

#list data structure here
doubly_linked_list:doubly_linked_list.c header.h prototype.h list_prototype.h
	gcc -c doubly_linked_list.c header.h prototype.h list_prototype.h
array_list:array_list.c header.h prototype.h list_prototype.h
	gcc -c array_list.c header.h prototype.h list_prototype.h
linked_list:linked_list.c header.h prototype.h list_prototype.h
	gcc -c linked_list.c header.h prototype.h list_prototype.h
self_organizing_list:self_organizing_list.c header.h prototype.h list_prototype.h
	gcc -c self_organizing_list.c header.h prototype.h list_prototype.h
skip_list:skip_list.c header.h prototype.h list_prototype.h
	gcc -c skip_list.c header.h prototype.h list_prototype.h
unrolled_linked_list:unrolled_linked_list.c header.h prototype.h list_prototype.h
	gcc -c unrolled_linked_list.c header.h prototype.h list_prototype.h
vlist:vlist.c header.h prototype.h list_prototype.h
	gcc -c vlist.c header.h prototype.h list_prototype.h
conc_tree_list:conc_tree_list.c header.h prototype.h list_prototype.h
	gcc -c conc_tree_list.c header.h prototype.h list_prototype.h
xor_linked_list:xor_linked_list.c header.h prototype.h list_prototype.h
	gcc -c xor_linked_list.c header.h prototype.h list_prototype.h
zipper:zipper.c header.h prototype.h list_prototype.h
	gcc -c zipper.c header.h prototype.h list_prototype.h
doubly_connected_edge_list:doubly_connected_edge_list.c header.h prototype.h list_prototype.h
	gcc -c doubly_connected_edge_list.c header.h prototype.h list_prototype.h
difference_list:difference_list.c header.h prototype.h list_prototype.h
	gcc -c difference_list.c header.h prototype.h list_prototype.h
free_list:free_list.c header.h prototype.h list_prototype.h 
	gcc -c free_list.c header.h prototype.h list_prototype.h

#tree data structure option here
binary_trees_option:binary_trees_option.c header.h prototype.h tree_prototype.h
	gcc -c binary_trees_option.c header.h prototype.h tree_prototype.h
b_trees_option:b_trees_option.c header.h prototype.h tree_prototype.h
	gcc -c b_trees_option.c header.h prototype.h tree_prototype.h
heaps_option:heaps_option.c header.h prototype.h tree_prototype.h
	gcc -c heaps_option.c header.h prototype.h tree_prototype.h
trees_option:trees_option.c header.h prototype.h tree_prototype.h
	gcc -c trees_option.c header.h prototype.h tree_prototype.h
multiway_trees_option:multiway_trees_option.c header.h prototype.h tree_prototype.h
	gcc -c multiway_trees_option.c header.h prototype.h tree_prototype.h
space_partitioning_trees_option:space_partitioning_trees_option.c header.h prototype.h tree_prototype.h
	gcc -c space_partitioning_trees_option.c header.h prototype.h tree_prototype.h
application_specific_trees_option:application_specific_trees_option.c header.h prototype.h tree_prototype.h
	gcc -c application_specific_trees_option.c header.h prototype.h tree_prototype.h

#hash data structure option here
bloom_filter:bloom_filter.c header.h prototype.h hash_prototype.h
	gcc -c bloom_filter.c header.h prototype.h hash_prototype.h
count_min_sketch:count_min_sketch.c header.h prototype.h hash_prototype.h
	gcc -c count_min_sketch.c header.h prototype.h hash_prototype.h
distributed_hash_table:distributed_hash_table.c header.h prototype.h hash_prototype.h
	gcc -c distributed_hash_table.c header.h prototype.h hash_prototype.h
double_hashing:double_hashing.c header.h prototype.h hash_prototype.h
	gcc -c double_hashing.c header.h prototype.h hash_prototype.h
dynamic_perfect_hash_table:dynamic_perfect_hash_table.c header.h prototype.h hash_prototype.h
	gcc -c dynamic_perfect_hash_table.c header.h prototype.h hash_prototype.h
hash_array_mapped_trie:hash_array_mapped_trie.c header.h prototype.h hash_prototype.h
	gcc -c hash_array_mapped_trie.c header.h prototype.h hash_prototype.h
hash_list:hash_list.c header.h prototype.h hash_prototype.h 
	gcc -c hash_list.c header.h prototype.h hash_prototype.h
hash_table:hash_table.c header.h prototype.h hash_prototype.h
	gcc -c hash_table.c header.h prototype.h hash_prototype.h
hash_tree:hash_tree.c header.h prototype.h hash_prototype.h
	gcc -c hash_tree.c header.h prototype.h hash_prototype.h
hash_trie:hash_trie.c header.h prototype.h hash_prototype.h
	gcc -c hash_trie.c header.h prototype.h hash_prototype.h
koorde:koorde.c header.h prototype.h hash_prototype.h
	gcc -c koorde.c header.h prototype.h hash_prototype.h
prefix_hash_tree:prefix_hash_tree.c header.h prototype.h hash_prototype.h
	gcc -c prefix_hash_tree.c header.h prototype.h hash_prototype.h
rolling_hash:rolling_hash.c header.h prototype.h hash_prototype.h
	gcc -c rolling_hash.c header.h prototype.h hash_prototype.h
minhash:minhash.c header.h prototype.h hash_prototype.h
	gcc -c minhash.c header.h prototype.h hash_prototype.h
quotient_filter:quotient_filter.c header.h prototype.h hash_prototype.h
	gcc -c quotient_filter.c header.h prototype.h hash_prototype.h 
ctrie:ctrie.c header.h prototype.h hash_prototype.h
	gcc -c ctrie.c header.h prototype.h hash_prototype.h

#graph data structure option here
graph:graph.c header.h prototype.h graph_prototype.h
	gcc -c graph.c header.h prototype.h graph_prototype.h
adjacency_list:adjacency_list.c header.h prototype.h graph_prototype.h
	gcc -c adjacency_list.c header.h prototype.h graph_prototype.h
adjacency_matrix:adjacency_matrix.c header.h prototype.h graph_prototype.h
	gcc -c adjacency_matrix.c header.h prototype.h graph_prototype.h 
graph_structured_stack:graph_structured_stack.c header.h prototype.h graph_prototype.h
	gcc -c graph_structured_stack.c header.h prototype.h graph_prototype.h 
scene_graph:scene_graph.c header.h prototype.h graph_prototype.h
	gcc -c scene_graph.c header.h prototype.h graph_prototype.h 
binary_decision_diagram:binary_decision_diagram.c header.h prototype.h graph_prototype.h
	gcc -c binary_decision_diagram.c header.h prototype.h graph_prototype.h
zero_suppressed_decision_diagram:zero_suppressed_decision_diagram.c header.h prototype.h graph_prototype.h
	gcc -c zero_suppressed_decision_diagram.c header.h prototype.h graph_prototype.h
and_inverter_graph:and_inverter_graph.c header.h prototype.h graph_prototype.h
	gcc -c and_inverter_graph.c header.h prototype.h graph_prototype.h 
directed_graph:directed_graph.c header.h prototype.h graph_prototype.h
	gcc -c directed_graph.c header.h prototype.h graph_prototype.h
directed_acyclic_graph:directed_acyclic_graph.c header.h prototype.h graph_prototype.h
	gcc -c directed_acyclic_graph.c header.h prototype.h graph_prototype.h
propositional_directed_acyclic_graph:propositional_directed_acyclic_graph.c header.h prototype.h graph_prototype.h
	gcc -c propositional_directed_acyclic_graph.c header.h prototype.h graph_prototype.h 
multigraph:multigraph.c header.h prototype.h graph_prototype.h
	gcc -c multigraph.c header.h prototype.h graph_prototype.h
hypergraph:hypergraph.c header.h prototype.h graph_prototype.h 
	gcc -c hypergraph.c header.h prototype.h graph_prototype.h


#other data structure option here
lightmap:lightmap.c header.h prototype.h other_prototype.h
	gcc -c lightmap.c header.h prototype.h other_prototype.h
winged_edge:winged_edge.c header.h prototype.h other_prototype.h
	gcc -c winged_edge.c header.h prototype.h other_prototype.h
#doubly_connected_edge_list:doubly_connected_edge_list.c header.h prototype.h other_prototype.h
#	gcc -c doubly_connected_edge_list.c header.h prototype.h other_prototype.h
quad_edge:quad_edge.c header.h prototype.h other_prototype.h
	gcc -c quad_edge.c header.h prototype.h other_prototype.h
routing_table:routing_table.c header.h prototype.h other_prototype.h 
	gcc -c routing_table.c header.h prototype.h other_prototype.h
symbol_table:symbol_table.c header.h prototype.h other_prototype.h
	gcc -c symbol_table.c header.h prototype.h other_prototype.h

#binary tree option here
aa_tree:aa_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c aa_tree.c header.h prototype.h bin_trees_prototype.h
avl_tree:avl_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c avl_tree.c header.h prototype.h bin_trees_prototype.h
binary_search_tree:binary_search_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c binary_search_tree.c header.h prototype.h bin_trees_prototype.h
cartesian_tree:cartesian_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c cartesian_tree.c header.h prototype.h bin_trees_prototype.h
left_child_right_sibiling_tree:left_child_right_sibiling_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c left_child_right_sibiling_tree.c header.h prototype.h bin_trees_prototype.h
order_statistic_tree:order_statistic_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c order_statistic_tree.c header.h prototype.h bin_trees_prototype.h
pagoda:pagoda.c header.h prototype.h bin_trees_prototype.h
	gcc -c pagoda.c header.h prototype.h bin_trees_prototype.h
randomized_binary_search_tree:randomized_binary_search_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c randomized_binary_search_tree.c header.h prototype.h bin_trees_prototype.h
red_black_tree:red_black_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c red_black_tree.c header.h prototype.h bin_trees_prototype.h
rope:rope.c header.h prototype.h bin_trees_prototype.h
	gcc -c rope.c header.h prototype.h bin_trees_prototype.h
scapegoat_tree:scapegoat_tree.c header.h prototype.h bin_trees_prototype.h 
	gcc -c scapegoat_tree.c header.h prototype.h bin_trees_prototype.h
self_balancing_binary_search_tree:self_balancing_binary_search_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c self_balancing_binary_search_tree.c header.h prototype.h bin_trees_prototype.h
splay_tree:splay_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c splay_tree.c header.h prototype.h bin_trees_prototype.h
t_tree:t_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c t_tree.c header.h prototype.h bin_trees_prototype.h
tango_tree:tango_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c tango_tree.c header.h prototype.h bin_trees_prototype.h
threaded_binary_tree:threaded_binary_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c threaded_binary_tree.c header.h prototype.h bin_trees_prototype.h
top_tree:top_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c top_tree.c header.h prototype.h bin_trees_prototype.h 
treap:treap.c header.h prototype.h bin_trees_prototype.h
	gcc -c treap.c header.h prototype.h bin_trees_prototype.h
wavl_tree:wavl_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c wavl_tree.c header.h prototype.h bin_trees_prototype.h 
weight_balanced_tree:weight_balanced_tree.c header.h prototype.h bin_trees_prototype.h
	gcc -c weight_balanced_tree.c header.h prototype.h bin_trees_prototype.h

#b trees option here
b_tree:b_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c b_tree.c header.h prototype.h b_trees_prototype.h
b_plus_tree:b_plus_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c b_plus_tree.c header.h prototype.h b_trees_prototype.h
b_star_tree:b_star_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c b_star_tree.c header.h prototype.h b_trees_prototype.h
b_sharp_tree:b_sharp_tree.c header.h prototype.h b_trees_prototype.h 
	gcc -c b_sharp_tree.c header.h prototype.h b_trees_prototype.h
dancing_tree:dancing_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c dancing_tree.c header.h prototype.h b_trees_prototype.h
b_2_3_tree:b_2_3_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c b_2_3_tree.c header.h prototype.h b_trees_prototype.h
b_2_3_4_tree:b_2_3_4_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c b_2_3_4_tree.c header.h prototype.h b_trees_prototype.h
queap:queap.c header.h prototype.h b_trees_prototype.h
	gcc -c queap.c header.h prototype.h b_trees_prototype.h
fusion_tree:fusion_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c fusion_tree.c header.h prototype.h b_trees_prototype.h
bx_tree:bx_tree.c header.h prototype.h b_trees_prototype.h
	gcc -c bx_tree.c header.h prototype.h b_trees_prototype.h 
alist:alist.c header.c header.h prototype.h b_trees_prototype.h
	gcc -c alist.c header.h prototype.h b_trees_prototype.h

#heap option here
heap:heap.c header.h prototype.h heaps_prototype.h
	gcc -c heap.c header.h prototype.h heaps_prototype.h
binary_heap:binary_heap.c header.h prototype.h heaps_prototype.h
	gcc -c binary_heap.c header.h prototype.h heaps_prototype.h
weak_heap:weak_heap.c header.h prototype.h heaps_prototype.h
	gcc -c weak_heap.c header.h prototype.h heaps_prototype.h
binomial_heap:binomial_heap.c header.h prototype.h heaps_prototype.h 
	gcc -c binomial_heap.c header.h prototype.h heaps_prototype.h
fibonacci_heap:fibonacci_heap.c header.h prototype.h heaps_prototype.h
	gcc -c fibonacci_heap.c header.h prototype.h heaps_prototype.h
af_heap:af_heap.c header.h prototype.h heaps_prototype.h 
	gcc -c af_heap.c header.h prototype.h heaps_prototype.h 
leonardo_heap:leonardo_heap.c header.h prototype.h heaps_prototype.h
	gcc -c leonardo_heap.c header.h prototype.h heaps_prototype.h 
h_2_3_heap:h_2_3_heap.c header.h prototype.h heaps_prototype.h
	gcc -c h_2_3_heap.c header.h prototype.h heaps_prototype.h
soft_heap:soft_heap.c header.h prototype.h heaps_prototype.h
	gcc -c soft_heap.c header.h prototype.h heaps_prototype.h
pairing_heap:pairing_heap.c header.h prototype.h heaps_prototype.h
	gcc -c pairing_heap.c header.h prototype.h heaps_prototype.h
leftlist_heap:leftlist_heap.c header.h prototype.h heaps_prototype.h
	gcc -c leftlist_heap.c header.h prototype.h heaps_prototype.h
#treap:treap.c header.h prototype.h heaps_prototype.h
#	gcc -c treap.c header.h prototype.h heaps_prototype.h
beap:beap.c header.h prototype.h heaps_prototype.h
	gcc -c beap.c header. prototype.h heaps_prototype.h
skew_heap:skew_heap.c header.h prototype.h heaps_prototype.h
	gcc -c skew_heap.c header.h prototype.h heaps_prototype.h
ternary_heap:ternary_heap.c header.h prototype.h heaps_prototype.h
	gcc -c ternary_heap.c header.h prototype.h heaps_prototype.h
d_ary_heap:d_ary_heap.c header.h prototype.h heaps_prototype.h
	gcc -c d_ary_heap.c header.h prototype.h heaps_prototype.h
brodal_heap:brodal_heap.c header.h prototype.h heaps_prototype.h
	gcc -c brodal_heap.c header.c prototype.h heaps_prototype.h

#trees option here
trie:trie.c header.c prototype.h trees_prototype.h
	gcc -c trie.c header.h prototype.h trees_prototype.h
radix_tree:radix_tree.c header.h prototype.h trees_prototype.h
	gcc -c radix_tree.c header.h prototype.h trees_prototype.h
suffix_tree:suffix_tree.c header.h prototype.h trees_prototype.h
	gcc -c suffix_tree.c header.h prototype.h trees_prototype.h
suffix_array:suffix_array.c header.h prototype.h trees_prototype.h
	gcc -c suffix_array.c header.h prototype.h trees_prototype.h
compressed_suffix_array:compressed_suffix_array.c header.h prototype.h trees_prototype.h
	gcc -c compressed_suffix_array.c header.h prototype.h trees_prototype.h
fm_index:fm_index.c header.h prototype.h trees_prototype.h
	gcc -c fm_index.c header.h prototype.h trees_prototype.h
generalised_suffix_tree:generalised_suffix_tree.c header.h prototype.h trees_prototype.h
	gcc -c generalised_suffix_tree.c header.h prototype.h trees_prototype.h
b_trie:b_trie.c header.h prototype.h trees_prototype.h
	gcc -c b_trie.c header.h prototype.h trees_prototype.h
judy_array:judy_array.c header.h prototype.h trees_prototype.h
	gcc -c judy_array.c header.h prototype.h trees_prototype.h
x_fast_trie:x_fast_trie.c header.h prototype.h trees_prototype.h
	gcc -c x_fast_trie.c header.h prototype.h trees_prototype.h
y_fast_trie:y_fast_trie.c header.h prototype.h trees_prototype.h
	gcc -c y_fast_trie.c header.h prototype.h trees_prototype.h
merkle_tree:merkle_tree.c header.h prototype.h trees_prototype.h
	gcc -c merkle_tree.c header.h prototype.h trees_prototype.h
#ctrie:ctrie.c header.h prototype.h trees_prototype.h
#	gcc -c ctrie.c header.h prototype.h trees_prototype.h

#multiway trees option here
ternary_tree:ternary_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c ternary_tree.c header.h prototype.h multi_trees_prototype.h
k_ary_tree:k_ary_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c k_ary_tree.c header.h prototype.h multi_trees_prototype.h
and_or_tree:and_or_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c and_or_tree.c header.h prototype.h multi_trees_prototype.h
a_b_tree:a_b_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c a_b_tree.c header.h prototype.h multi_trees_prototype.h
link_cut_tree:link_cut_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c link_cut_tree.c header.h prototype.h multi_trees_prototype.h
spqr_tree:spqr_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c spqr_tree.c header.h prototype.h multi_trees_prototype.h
spaghetti_stack:spaghetti_stack.c header.h prototype.h multi_trees_prototype.h
	gcc -c spaghetti_stack.c header.h prototype.h multi_trees_prototype.h
disjoint_set_data_structure:disjoint_set_data_structure.c header.h prototype.h multi_trees_prototype.h
	gcc -c disjoint_set_data_structure.c header.h prototype.h multi_trees_prototype.c 
#fusion_tree:fusion_tree.c header.h prototype.h multi_trees_prototype.h
#	gcc -c fusion_tree.c header.h prototype.h multi_trees_prototype.h
enfilade:enfilade.c header.h prototype.h multi_trees_prototype.h 
	gcc -c enfilade.c header.h prototype.h multi_trees_prototype.h
exponential_tree:exponential_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c exponential_tree.c header.h prototype.h multi_trees_prototype.h
fenwick_tree:fenwick_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c fenwick_tree.c header.h prototype.h multi_trees_prototype.h
van_emde_boas_tree:van_emde_boas_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c van_emde_boas_tree.c header.h prototype.h multi_trees_prototype.h
rose_tree:rose_tree.c header.h prototype.h multi_trees_prototype.h
	gcc -c rose_tree.c header.h prototype.h multi_trees_prototype.h

#space partitioning trees option here
segment_tree:segment_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c segment_tree.c header.h prototype.h space_part_trees_prototype.h
interval_tree:interval_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c interval_tree.c header.h prototype.h space_partitioning_trees_prototype.h
range_tree:range_tree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c range_tree.c header.h prototype.h space_partitioning_trees_prototype.h
bin:bin.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c bin.c header.h prototype.h space_partitioning_trees_prototype.h
k_d_tree:k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
implicit_k_d_tree:implicit_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c implicit_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
min_max_k_d_tree:min_max_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c min_max_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
relaxed_k_d_tree:relaxed_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c relaxed_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
adaptive_k_d_tree:adaptive_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c adaptive_k_d_tree.c header.h prototype.h space_partitioning_trees_prototype.h
quadtree:quadtree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c quadtree.c header.h prototype.h space_partitioning_trees_prototype.h
octree:octree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c octree.cc header.h prototype.h space_partitioning_trees_prototype.h
linear_octree:linear_octree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c linear_octree.c header.h prototype.h space_partitioning_trees_prototype.h
z_order:z_order.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c z_order.c header.h prototype.h space_partitioning_trees_prototype.h
ub_tree:ub_tree.c header.h prototype.h space_partitioning_trees_prototype.h
	gcc -c ub_tree.c header.h prototype.h space_partitioning_trees_prototype.h
r_tree:r_tree.c header.h prototype.h space_speci_trees_prototype.h
	gcc -c header.h prototype.h space_part_trees_prototype.h
r_plus_tree:r_plus_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c r_plus_tree.c header.h prototype.h space_part_trees_prototype.h
r_star_tree:r_star_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c r_star_tree.c header.h prototype.h space_part_trees_prototype.h
hilbert_r_tree:hilbert_r_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c hilbert_r_tree.c header.h prototype.h space_part_trees_prototype.h
x_tree:x_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c x_tree.c header.h prototype.h space_part_trees_prototype.h
metric_tree:metric_tree. header.h prototype.h space_part_trees_prototype.h
	gcc -c metric_tree.c header.h prototype.h space_part_trees_prototype.h
cover_tree:cover_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c cover_tree.c header.h prototype.h space_part_trees_prototype.h
m_tree:m_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c m_tree.c header.h prototype.h space_part_trees_prototype.h
vp_tree:vp_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c vp_tree.c header.h prototype.h space_part_trees_prototype.h
bk_tree:bk_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c bk_tree.c header.h prototype.h space_part_trees_prototype.h
bounding_interval_hierarchy:bounding_interval_hierarchy.c header.h prototype.h space_part_trees_prototype.h
	gcc -c bounding_interval_hierarchy.c header.h prototype.h space_part_trees_prototype.h
bounding_volume_hierarchy:bounding_volume_hierarchy.c header.h prototype.h space_part_trees_prototype.h
	gcc -c bounding_volume_hierarchy.c header.h prototype.h space_part_trees_prototype.h
bsp_tree:bsp_tree.c header.h prototype.h space_part_trees_prototype.h 
	gcc -c bsp_tree.c header.h prototype.h space_part_trees_prototype.h 
rapidly_exploring_random_tree:rapidly_exploring_random_tree.c header.h prototype.h space_part_trees_prototype.h
	gcc -c rapidly_exploring_random_tree.c header.h prototype.h space_part_trees_prototype.h

#application specific trees option here
abstract_syntax_tree:abstract_syntax_tree.h header.h prototype.h app_speci_trees_prototype.h
	gcc -c abstract_syntax_tree.c header.h prototype.h app_speci_trees_prototype.h
parse_tree:parse_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c parse_tree.c header.h prototype.h app_speci_trees_prototype.h
decision_tree:decision_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c decision_tree.c header.h prototype.h app_speci_trees_prototype.h
alternating_decision_tree:alternating_decision_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c alternating_decision_tree.c header.h prototype.h app_speci_trees_prototype.h
minimax_tree:minimax_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c minimax_tree.c header.h prototype.h app_speci_trees_prototype.h
expectiminimax_tree:expectiminimax_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c expectiminimax_tree.c header.h prototype.h app_speci_trees_prototype.h
finger_tree:finger_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c finger_tree.c header.h prototype.h app_speci_trees_prototype.h
expression_tree:expression_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c expression_tree.c header.h prototype.h app_speci_trees_prototype.h
log_structured_merge_tree:log_structured_merge_tree.c header.h prototype.h app_speci_trees_prototype.h
	gcc -c log_structured_merge_tree.c header.h prototype.h app_speci_trees_prototype.h
lexicographic_search_tree:lexicographic_search_tree.c header.h prototype.h app_speci_trees_prototype.h 
	gcc -c lexicographic_search_tree.c header.h prototype.h app_speci_trees_prototype.h
